name: dockerlogin


on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  LogintodockerhubDEV:
    runs-on: ubuntu-latest
    environment: digvijaydev
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
    - name: Docker Pull
      run: docker pull hello-world
    - name: Docker Tag
      run: docker tag digvijaygit2024/dockerdemorepository
    - name: Docker Push
      run: docker pull digvijaygit2024/dockerdemorepository
  LogintodockerhubQA:
    runs-on: ubuntu-latest
    environment: digvijayqa
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
